server:
  port: 8500 #端口号

#指定当前eureka注册中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8035/eureka

spring: #项目服务名
    application:
      name: api-provider

    datasource: #数据库配置
      url: jdbc:mysql://192.168.1.220:3306/qycl_qd2_0708?characterEncoding=UTF-8&autoReconnect=true #换成自己的数据库地址
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: karakal

#es配置
    data:
      elasticsearch:
        cluster-name: myes
        cluster-nodes: 127.0.0.1:9300
        repositories:
          enabled: true
