server:
  #端口号
  port: 8035

eureka:
  instance:
    hostname: server1

  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      #自身不再向eureka 注册
    register-with-eureka: false
    #启动时禁用client的注册
    fetch-registry: false
  server:
    #在Eureka服务器获取不到集群里对等服务器上的实例时，需要等待的时间，单位为毫秒
    wait-time-in-ms-when-sync-empty: 5

spring:
    application:
      name: eureka-server-cluster
